### ISSUE TITLE
Cannot delete The WIRED CD

### ISSUE THREAD

**Issue by nathan323** [feross/webtorrent-desktop#905]
The WIRED CD is persistently remaining on my hard drive, despite removing it from Webtorrent client and  deleting it from hard drive. When I delete it the files to the Recycle Bin, it doesn't show any error, but doesn't delete, doesn't show up in Recycle Bin. If I attempt to delete again it reports File Not Found dialog, refreshing Explorer doesn't make it disappear. Approx. 30 minutes later I can delete it and it will disappear, but after restarting computer, it reappears.

Version 0.14.0 (0.96.4)
Windows 7 64

**Comment by dcposch** [comment]
Just tried this on Mac, and I can't reproduce it.

> Approx. 30 minutes later I can delete it and it will disappear, but after restarting computer, it reappears.

That is **very** weird.

Could you double check that it's deleted from WebTorrent?

**Comment by nathan323** [comment]
Yes definitely deleted from WebTorrent. I also have a program called LockHunter, which reports no processes are using folder.
Very weird indeed, never seen this before.
This is the Properties page of folder:
![image](https://cloud.githubusercontent.com/assets/16442365/18311286/d4cf5738-7546-11e6-87a3-19ec0e9d4105.png)

**Comment by demoneaux** [comment]
I ran into this issue too. Running `rimraf` seemed to remove it. Not too sure what happened, will try digging into it.

**Comment by nathan323** [comment]
Ok thanks. Can you tell me how to use [rimraf?](https://github.com/isaacs/rimraf)

**Comment by demoneaux** [comment]
Just install it and use it to delete the folder:

```sh
npm install -g rimraf
rimraf "path/to/The WIRED CD - ..."
```

**Comment by nathan323** [comment]
So I create a batch file with your code, and run in the same directory as rimraf.js?

**Comment by demoneaux** [comment]
Nope, you can just enter those commands in the command prompt/terminal, if you have npm installed.

```sh
npm install -g rimraf # installs the rimraf library globally
rimraf "path/to/The WIRED CD - ..." # uses rimraf to delete the wired cd
```

**Comment by nathan323** [comment]
Got it, cool. I didn't have npm (or know anything about it), I've now installed Node.js

I've created a Windows Explorer context menu entry that automates the rimraf operation, if anyone is interested. Right-clicking on any file or folder will give an option to delete with rimraf (with a confirmation dialog first just to be safe :) It involves an AutoHotkey script and a registry file, zipped [here](https://drive.google.com/open?id=0BxzKibd8YxtJM2dGdFo2cVhyWXM).

**Comment by nathan323** [comment]
Btw, I forgot to report2 days ago - the same thing happened when I upgraded from Version 0.14.0 (0.96.4) to Version 0.17.0 (0.97.1).
When downloading The Wired CD torrent for a moment, then cancelling download and deleting torrent, the The Wired CD folder cannot be deleted (except with [rimraf](https://github.com/isaacs/rimraf)).

**Comment by feross** [comment]
Apparently this issue is due to the way the Wired torrent name ends in a period character (`.`). Windows is supposed to be able to handle paths with periods in them according to [this KB article](https://support.microsoft.com/en-us/kb/177506), but the [reality is different](http://stackoverflow.com/questions/4075753/how-to-delete-a-folder-that-name-ended-with-a-dot).

We're now using `rimraf` instead of `fs-extra` inside of WebTorrent Desktop, as of version 0.17.1, so hopefully this won't be an issue for you anymore.

@nathan323 @demoneaux Can you give version 0.17.1 a try and let me know if deleting the Wired torrent works now? https://webtorrent.io/desktop/

**Comment by feross** [comment]
Actually, it looks like we're still using Electron's `moveToTrash` which exhibits the isse.

Let me try another fix: Never allow torrents to end with a `.` character.

**Comment by feross** [comment]
Sent a PR! https://github.com/feross/webtorrent-desktop/pull/1013

**Comment by nathan323** [comment]
Hehe now rimraf won't delete Wired CD either :s 

0.17.1

**Comment by feross** [comment]
@nathan323 Updating to the latest version of WebTorrent should fix the issue.

**Comment by nathan323** [comment]
Just a note that this isn't fixed for me. I have just updated to 0.18.0, no change.
Can't delete normally/with rimraf. If I try to remove the last period from the filename (after Share), it asks if I want to change the extension, so definitely an issue with filename with period.\But the name change is not allowed as "Couldn't find this item", but it remains, even after reboot.
